# Import the compiled Rust extension as a top-level module
import bunker_stats_rs  # type: ignore[attr-defined]

from bunker_stats_rs import (  # re-export selected functions
    mean_np,
    std_np,
    var_np,
    zscore_np,
    percentile_np,
    iqr_np,
    mad_np,
    rolling_mean_np,
    rolling_std_np,
    rolling_zscore_np,
    ewma_np,
    welford_np,
    sign_mask_np,
    demean_with_signs_np,
    iqr_outliers_np,
    zscore_outliers_np,
    minmax_scale_np,
    robust_scale_np,
    winsorize_np,
    quantile_bins_np,
    diff_np,
    pct_change_np,
    cumsum_np,
    cummean_np,
    ecdf_np,
    cov_np,
    corr_np,
    cov_matrix_np,
    corr_matrix_np,
    rolling_cov_np,
    rolling_corr_np,
    kde_gaussian_np,
)

from . import pandas_helpers as pandas

__all__ = [
    "mean_np",
    "std_np",
    "var_np",
    "zscore_np",
    "percentile_np",
    "iqr_np",
    "mad_np",
    "rolling_mean_np",
    "rolling_std_np",
    "rolling_zscore_np",
    "ewma_np",
    "welford_np",
    "sign_mask_np",
    "demean_with_signs_np",
    "iqr_outliers_np",
    "zscore_outliers_np",
    "minmax_scale_np",
    "robust_scale_np",
    "winsorize_np",
    "quantile_bins_np",
    "diff_np",
    "pct_change_np",
    "cumsum_np",
    "cummean_np",
    "ecdf_np",
    "cov_np",
    "corr_np",
    "cov_matrix_np",
    "corr_matrix_np",
    "rolling_cov_np",
    "rolling_corr_np",
    "kde_gaussian_np",
    "pandas",
]
